description: ""
content:
  application/json:
    schema:
      title: CreateTaskRequest
      required:
        - name
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        assignees:
          type: array
          items:
            type: integer
            contentEncoding: int32
          description: ""
        archived:
          type: boolean
        group_assignees:
          type: array
          items:
            type: string
          description: "Assign multiple user groups to the task."
        tags:
          type: array
          items:
            type: string
          description: ""
        status:
          type: string
        priority:
          type:
            - integer
            - null
          contentEncoding: int32
        due_date:
          type: integer
          contentEncoding: int64
        due_date_time:
          type: boolean
        time_estimate:
          type: integer
          contentEncoding: int32
        start_date:
          type: integer
          contentEncoding: int64
        start_date_time:
          type: boolean
        points:
          type: number
          description: "Add Sprint Points to the task."
        notify_all:
          type: boolean
          description: "If `notify_all` is true, notifications will be sent to everyone including the creator of the comment."
        parent:
          description: "You can create a subtask by including an existing task ID.\\\n \\\nThe `parent` task ID you include can be a subtask, but must be in the same List specified in the path parameter."
          type:
            - string
            - null
        markdown_content:
          type: string
          description: "Markdown formatted description for the task. If both `markdown_content` and `description` are provided, `markdown_content` will be used instead of `description`."
        links_to:
          description: "Include a task ID to create a linked dependency with your new task."
          type:
            - string
            - null
        check_required_custom_fields:
          description: "When creating a task via API any required Custom Fields are ignored by default (`false`).\\\n \\\nYou can enforce required Custom Fields by including `check_required_custom_fields: true`."
          type: boolean
        custom_fields:
          type: array
          items:
            title: SetCustomFieldValueOnCreateTaskRequest
            anyOf:
              -
                type: object
                title: "URL Custom Field"
                description: "The `value` must be a string with a valid URL."
                required:
                  - id
                  - value
                properties:
                  id:
                    type: string
                  value:
                    type:
                      - string
                      - null
                    example: https://clickup.com/api
              -
                type: object
                title: "Dropdown Custom Field"
                description: "Enter the universal unique identifier (UUID) of the dropdown menu option you want to set. You can find the UUIDs available for each Dropdown Custom Field using [Get Accessible Custom Fields.](ref:getaccessiblecustomfields) New Dropdown Custom Field options cannot be created from this request."
                required:
                  - id
                  - value
                properties:
                  id:
                    type: string
                  value:
                    type:
                      - string
                      - null
                    example: uuid1234
              -
                type: object
                title: "Email Custom Field"
                description: "The `value` must be a string with a valid email address."
                required:
                  - id
                  - value
                properties:
                  id:
                    type: string
                  value:
                    type:
                      - string
                      - null
                    example: "user@company.com"
              -
                type: object
                title: "Phone Custom Field"
                description: "The `value` must be a string with a valid country code."
                required:
                  - id
                  - value
                properties:
                  id:
                    type: string
                  value:
                    type:
                      - string
                      - null
                    example: "+1 123 456 7890"
              -
                type: object
                title: "Date Custom Field"
                description: "The `value` must be Unix time in milliseconds. To display the time in a Date Custom Field in ClickUp, you must include `time: true` in the `value_options` property."
                required:
                  - id
                  - value
                properties:
                  id:
                    type: string
                  value:
                    type:
                      - integer
                      - null
                    format: int32
                    example: 1667367645000
                  value_options:
                    $ref: "./value_options.yaml"
              -
                type: object
                title: "Short or Long Text Custom Field"
                description: "Enter a string of text."
                required:
                  - id
                  - value
                properties:
                  id:
                    type: string
                  value:
                    type:
                      - string
                      - null
                    example: "This is short or long text in a Custom Field."
              -
                type: object
                title: "Number Custom Field"
                description: "Enter a number."
                required:
                  - id
                  - value
                properties:
                  id:
                    type: string
                  value:
                    type:
                      - number
                      - null
                    example: -28
              -
                type: object
                title: "Money Custom Field"
                description: "You can set an amount, but not the currency of a Money Custom Field via the API. You can check the currency of a Money Custom Field using [Get Accessible Custom Fields.](ref:getaccessiblecustomfields)"
                required:
                  - id
                  - value
                properties:
                  id:
                    type: string
                  value:
                    type:
                      - number
                      - null
                    example: 8000
              -
                type: object
                title: "Task Relationship Custom Field"
                description: "Enter an array of task ids in the `add` property to add them to a Task Relationship Custom Field. Enter them into the `rem` property to remove tasks from the Relationship. Task Relationship Custom Fields are nullable: `\"value\": null`."
                required:
                  - id
                  - value
                properties:
                  id:
                    type: string
                  value:
                    $ref: "./value.yaml"
              -
                type: object
                title: "People Custom Field"
                description: "Enter an array of user ids or a Team id in the `add` property to add them to a People Custom Field. Enter them into the `rem` property to remove users from a People Custom Field. You can get a list of people in the Workspace using [Get Authorized Teams (Workspaces).](ref:getauthorizedteams) People Custom Fields are nullable: `\"value\": null`."
                required:
                  - id
                  - value
                properties:
                  id:
                    type: string
                  value:
                    $ref: "./value_2.yaml"
              -
                type: object
                title: "Emoji (Rating) Custom Field"
                description: "Enter an integer that is greater than or equal to zero and where the `count` property is greater than or equal to the `value`. You can find the `count` property for each Emoji (Rating) Custom Field using [Get Accessible Custom Fields.](ref:getaccessiblecustomfields)"
                required:
                  - id
                  - value
                properties:
                  id:
                    type: string
                  value:
                    type:
                      - integer
                      - null
                    format: int32
                    example: 4
              -
                type: object
                title: "Manual Progress Custom Field"
                description: "Enter a number between the `start` and `end` values of each Manual Progress Custom Field. For example, for a field with `start: 10` and `end: 30`, sending `current: 20` will be displayed as 50% complete in ClickUp. You can find the `start` and `end` values for each Manual Progress Custom Field using [Get Accessible Custom Fields.](ref:getaccessiblecustomfields) Manual Progress Custom Fields are nullable: `\"value\": null`."
                required:
                  - id
                  - value
                properties:
                  id:
                    type: string
                  value:
                    $ref: "./value_3.yaml"
              -
                type: object
                title: "Label Custom Field"
                description: "Enter an array of the universal unique identifiers (UUIDs) of the labels you want to apply. You can find the UUIDs available for each Label Custom Field using [Get Accessible Custom Fields.](ref:getaccessiblecustomfields) Label Custom Fields are nullable: `\"value\": null`."
                required:
                  - id
                  - value
                properties:
                  id:
                    type: string
                  value:
                    type: array
                    items:
                      type: string
                      example:
                        - uuid1234
                        - uuid9876
              -
                type: object
                title: "Location Custom Field"
                description: "Include the latitude, longitude, and formatted address as defined in the [Google Maps Geocoding API.](https://developers.google.com/maps/documentation/geocoding/overview)"
                required:
                  - id
                  - value
                properties:
                  id:
                    type: string
                  value:
                    $ref: "./value_4.yaml"
              -
                type: object
                title: "Button Custom Field"
                description: "Set a button Custom Field to `true` to \"click\" it. This will trigger the button's action as if it was clicked in the UI."
                required:
                  - id
                  - value
                properties:
                  id:
                    type: string
                  value:
                    type:
                      - boolean
                      - null
                    example: true
          description: "You can include one or more Custom Fields to set them when creating a new task.\\\n \\\nCustom Fields that use object and array type values are nullable by sending `\"value\": null`."
        custom_item_id:
          type: number
          description: "The custom task type ID for this task. A value of `null` (default) creates a standard task type \"Task\".\\\n \\\nTo get a list of available custom task type IDs for your Workspace, use the [Get Custom Task Types endpoint](ref:getcustomitems)."
      examples:
        -
          name: "New Task Name"
          description: "New Task Description"
          assignees:
            - 183
          archived: false
          group_assignees:
            - dd01f92f-48ca-446d-88a1-0beb0e8f5f14
          tags:
            - "tag name 1"
          status: Open
          priority: 3
          due_date: 1508369194377
          due_date_time: false
          time_estimate: 8640000
          start_date: 1567780450202
          start_date_time: false
          points: 3
          notify_all: true
          parent: null
          links_to: null
          check_required_custom_fields: true
          custom_fields:
            -
              id: 0a52c486-5f05-403b-b4fd-c512ff05131c
              value: 23
            -
              id: 03efda77-c7a0-42d3-8afd-fd546353c2f5
              value: "Text field input"
required: true
