openapi: 3.1.0
info:
  title: "ClickUp API v2 Reference"
  description: "The ClickUp API enables you to programmatically access and manage your ClickUp resources.\n\n## Authentication\nThe API supports two authentication methods:\n- **Personal API Token**: Use for testing and personal integrations. Add token to requests with header: `Authorization: pk_...`\n- **OAuth 2.0**: Required for building apps for other users. Uses authorization code flow.\n\n## Getting Started\nOur [Getting Started Guide](https://developer.clickup.com/docs/index) provides a comprehensive overview of how to use the ClickUp API.\n"
  contact:
    {}
  version: "2.0"
jsonSchemaDialect: https://json-schema.org/draft/2020-12/schema
servers:
  -
    url: https://api.clickup.com/api
    description: ClickUp
    variables:
      {}
paths:
  /v2/task/{task_id}/attachment:
    $ref: "./paths/v2_task_task_id_attachment.yaml"
  /v2/oauth/token:
    $ref: "./paths/v2_oauth_token.yaml"
  /v2/user:
    $ref: "./paths/v2_user.yaml"
  /v2/team:
    $ref: "./paths/v2_team.yaml"
  /v2/task/{task_id}/checklist:
    $ref: "./paths/v2_task_task_id_checklist.yaml"
  /v2/checklist/{checklist_id}:
    $ref: "./paths/v2_checklist_checklist_id.yaml"
  /v2/checklist/{checklist_id}/checklist_item:
    $ref: "./paths/v2_checklist_checklist_id_checklist_item.yaml"
  /v2/checklist/{checklist_id}/checklist_item/{checklist_item_id}:
    $ref: "./paths/v2_checklist_checklist_id_checklist_item_checklist_item_id.yaml"
  /v2/task/{task_id}/comment:
    $ref: "./paths/v2_task_task_id_comment.yaml"
  /v2/view/{view_id}/comment:
    $ref: "./paths/v2_view_view_id_comment.yaml"
  /v2/list/{list_id}/comment:
    $ref: "./paths/v2_list_list_id_comment.yaml"
  /v2/comment/{comment_id}:
    $ref: "./paths/v2_comment_comment_id.yaml"
  /v2/comment/{comment_id}/reply:
    $ref: "./paths/v2_comment_comment_id_reply.yaml"
  /v2/list/{list_id}/field:
    $ref: "./paths/v2_list_list_id_field.yaml"
  /v2/folder/{folder_id}/field:
    $ref: "./paths/v2_folder_folder_id_field.yaml"
  /v2/space/{space_id}/field:
    $ref: "./paths/v2_space_space_id_field.yaml"
  /v2/team/{team_id}/field:
    $ref: "./paths/v2_team_team_id_field.yaml"
  /v2/task/{task_id}/field/{field_id}:
    $ref: "./paths/v2_task_task_id_field_field_id.yaml"
  /v2/task/{task_id}/dependency:
    $ref: "./paths/v2_task_task_id_dependency.yaml"
  /v2/task/{task_id}/link/{links_to}:
    $ref: "./paths/v2_task_task_id_link_links_to.yaml"
  /v2/space/{space_id}/folder:
    $ref: "./paths/v2_space_space_id_folder.yaml"
  /v2/folder/{folder_id}:
    $ref: "./paths/v2_folder_folder_id.yaml"
  /v2/team/{team_id}/goal:
    $ref: "./paths/v2_team_team_id_goal.yaml"
  /v2/goal/{goal_id}:
    $ref: "./paths/v2_goal_goal_id.yaml"
  /v2/goal/{goal_id}/key_result:
    $ref: "./paths/v2_goal_goal_id_key_result.yaml"
  /v2/key_result/{key_result_id}:
    $ref: "./paths/v2_key_result_key_result_id.yaml"
  /v2/team/{team_id}/guest:
    $ref: "./paths/v2_team_team_id_guest.yaml"
  /v2/team/{team_id}/guest/{guest_id}:
    $ref: "./paths/v2_team_team_id_guest_guest_id.yaml"
  /v2/task/{task_id}/guest/{guest_id}:
    $ref: "./paths/v2_task_task_id_guest_guest_id.yaml"
  /v2/list/{list_id}/guest/{guest_id}:
    $ref: "./paths/v2_list_list_id_guest_guest_id.yaml"
  /v2/folder/{folder_id}/guest/{guest_id}:
    $ref: "./paths/v2_folder_folder_id_guest_guest_id.yaml"
  /v2/folder/{folder_id}/list:
    $ref: "./paths/v2_folder_folder_id_list.yaml"
  /v2/space/{space_id}/folder_template/{template_id}:
    $ref: "./paths/v2_space_space_id_folder_template_template_id.yaml"
  /v2/space/{space_id}/list:
    $ref: "./paths/v2_space_space_id_list.yaml"
  /v2/list/{list_id}:
    $ref: "./paths/v2_list_list_id.yaml"
  /v2/list/{list_id}/task/{task_id}:
    $ref: "./paths/v2_list_list_id_task_task_id.yaml"
  /v2/task/{task_id}/member:
    $ref: "./paths/v2_task_task_id_member.yaml"
  /v2/list/{list_id}/member:
    $ref: "./paths/v2_list_list_id_member.yaml"
  /v2/team/{team_id}/customroles:
    $ref: "./paths/v2_team_team_id_customroles.yaml"
  /v2/team/{team_id}/shared:
    $ref: "./paths/v2_team_team_id_shared.yaml"
  /v2/team/{team_id}/space:
    $ref: "./paths/v2_team_team_id_space.yaml"
  /v2/space/{space_id}:
    $ref: "./paths/v2_space_space_id.yaml"
  /v2/space/{space_id}/tag:
    $ref: "./paths/v2_space_space_id_tag.yaml"
  /v2/space/{space_id}/tag/{tag_name}:
    $ref: "./paths/v2_space_space_id_tag_tag_name.yaml"
  /v2/task/{task_id}/tag/{tag_name}:
    $ref: "./paths/v2_task_task_id_tag_tag_name.yaml"
  /v2/list/{list_id}/task:
    $ref: "./paths/v2_list_list_id_task.yaml"
  /v2/task/{task_id}:
    $ref: "./paths/v2_task_task_id.yaml"
  /v2/team/{team_Id}/task:
    $ref: "./paths/v2_team_team_id_task.yaml"
  /v2/task/{task_id}/merge:
    $ref: "./paths/v2_task_task_id_merge.yaml"
  /v2/task/{task_id}/time_in_status:
    $ref: "./paths/v2_task_task_id_time_in_status.yaml"
  /v2/task/bulk_time_in_status/task_ids:
    $ref: "./paths/v2_task_bulk_time_in_status_task_ids.yaml"
  /v2/team/{team_id}/taskTemplate:
    $ref: "./paths/v2_team_team_id_tasktemplate.yaml"
  /v2/list/{list_id}/taskTemplate/{template_id}:
    $ref: "./paths/v2_list_list_id_tasktemplate_template_id.yaml"
  /v2/folder/{folder_id}/list_template/{template_id}:
    $ref: "./paths/v2_folder_folder_id_list_template_template_id.yaml"
  /v2/space/{space_id}/list_template/{template_id}:
    $ref: "./paths/v2_space_space_id_list_template_template_id.yaml"
  /v2/team/{team_id}/seats:
    $ref: "./paths/v2_team_team_id_seats.yaml"
  /v2/team/{team_id}/plan:
    $ref: "./paths/v2_team_team_id_plan.yaml"
  /v2/team/{team_id}/group:
    $ref: "./paths/v2_team_team_id_group.yaml"
  /v2/team/{team_id}/custom_item:
    $ref: "./paths/v2_team_team_id_custom_item.yaml"
  /v2/group/{group_id}:
    $ref: "./paths/v2_group_group_id.yaml"
  /v2/group:
    $ref: "./paths/v2_group.yaml"
  /v2/task/{task_id}/time:
    $ref: "./paths/v2_task_task_id_time.yaml"
  /v2/task/{task_id}/time/{interval_id}:
    $ref: "./paths/v2_task_task_id_time_interval_id.yaml"
  /v2/team/{team_Id}/time_entries:
    $ref: "./paths/v2_team_team_id_time_entries.yaml"
  /v2/team/{team_id}/time_entries/{timer_id}:
    $ref: "./paths/v2_team_team_id_time_entries_timer_id.yaml"
  /v2/team/{team_id}/time_entries/{timer_id}/history:
    $ref: "./paths/v2_team_team_id_time_entries_timer_id_history.yaml"
  /v2/team/{team_id}/time_entries/current:
    $ref: "./paths/v2_team_team_id_time_entries_current.yaml"
  /v2/team/{team_id}/time_entries/tags:
    $ref: "./paths/v2_team_team_id_time_entries_tags.yaml"
  /v2/team/{team_Id}/time_entries/start:
    $ref: "./paths/v2_team_team_id_time_entries_start.yaml"
  /v2/team/{team_id}/time_entries/stop:
    $ref: "./paths/v2_team_team_id_time_entries_stop.yaml"
  /v2/team/{team_id}/user:
    $ref: "./paths/v2_team_team_id_user.yaml"
  /v2/team/{team_id}/user/{user_id}:
    $ref: "./paths/v2_team_team_id_user_user_id.yaml"
  /v2/team/{team_id}/view:
    $ref: "./paths/v2_team_team_id_view.yaml"
  /v2/space/{space_id}/view:
    $ref: "./paths/v2_space_space_id_view.yaml"
  /v2/folder/{folder_id}/view:
    $ref: "./paths/v2_folder_folder_id_view.yaml"
  /v2/list/{list_id}/view:
    $ref: "./paths/v2_list_list_id_view.yaml"
  /v2/view/{view_id}:
    $ref: "./paths/v2_view_view_id.yaml"
  /v2/view/{view_id}/task:
    $ref: "./paths/v2_view_view_id_task.yaml"
  /v2/team/{team_id}/webhook:
    $ref: "./paths/v2_team_team_id_webhook.yaml"
  /v2/webhook/{webhook_id}:
    $ref: "./paths/v2_webhook_webhook_id.yaml"
components:
  securitySchemes:
    Authorization_Token:
      name: Authorization
      type: apiKey
      in: header
      description: "API token required for authentication. Two types of tokens are supported:\n**Personal API Key** Obtain from ClickUp's settings page under 'Apps' and add it to the header as `Authorization: pk_...`\n**OAuth2 Access Token** Generated through the OAuth2 flow and add it to the header as `Authorization: Bearer {access_token}`"
security:
  -
    Authorization_Token:
      []
tags:
  - name: Authorization
  - name: Attachments
  - name: Comments
  - name: "Custom Task Types"
  - name: "Custom Fields"
  - name: Folders
  - name: Goals
  - name: Guests
  - name: Lists
  - name: Members
  - name: Roles
  - name: "Shared Hierarchy"
  - name: Spaces
  - name: Tags
  - name: Tasks
  - name: "Task Checklists"
  - name: "Task Relationships"
  - name: Templates
  - name: Workspaces
  - name: "User Groups"
  - name: "Time Tracking"
  - name: "Time Tracking (Legacy)"
  - name: Users
  - name: Views
  - name: Webhooks
