title: 20bbn28
required:
  - current_status
  - status_history
type: object
properties:
  current_status:
    $ref: "../../../shared/current_status.yaml"
  status_history:
    type: array
    items:
      $ref: "../../../shared/status_history.yaml"
    description: ""
examples:
  -
    current_status:
      status: open
      color: "#d3d3d3"
      total_time:
        by_minute: 21830
        since: "1604004420924"
    status_history:
      -
        status: open
        color: "#d3d3d3"
        type: open
        total_time:
          by_minute: 22276
          since: "1604004420925"
        orderindex: 0
      -
        status: "active status #2"
        color: "#5CF1D4"
        type: custom
        total_time:
          by_minute: 40109
          since: "1601597828835"
        orderindex: 4
