name: "statuses[]"
in: query
description: "Filter by statuses. Use `%20` to represent a space character. To include closed tasks, use the `include_closed` parameter. \\\n \\\nFor example: \\\n \\\n`?statuses[]=to%20do&statuses[]=in%20progress`"
style: form
explode: true
schema:
  type: array
  items:
    type: string
