name: "assignees[]"
in: query
description: "Filter by Assignees using people's ClickUp user id. For example: \\\n \\\n`?assignees[]=1234&assignees[]=5678`"
style: form
explode: true
schema:
  type: array
  items:
    type: string
